name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Lint
      run: poetry run ruff check .

    - name: Build package
      run: poetry build
